/********************************************************************************
** Form generated from reading UI file 'softKeyboard.ui'
**
** Created: Wed Dec 23 19:24:09 2015
**      by: Qt User Interface Compiler version 4.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SOFTKEYBOARD_H
#define UI_SOFTKEYBOARD_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QHeaderView>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QPushButton *pushButton_u;
    QPushButton *pushButton_t;
    QPushButton *pushButton_y;
    QPushButton *pushButton_i;
    QPushButton *pushButton_q;
    QPushButton *pushButton_zuokuo;
    QPushButton *pushButton_p;
    QPushButton *pushButton_r;
    QPushButton *pushButton_youkuo;
    QPushButton *pushButton_w;
    QPushButton *pushButton_o;
    QPushButton *pushButton_e;
    QPushButton *pushButton_j;
    QPushButton *pushButton_g;
    QPushButton *pushButton_h;
    QPushButton *pushButton_k;
    QPushButton *pushButton_a;
    QPushButton *pushButton_quote;
    QPushButton *pushButton_semicolon;
    QPushButton *pushButton_f;
    QPushButton *pushButton_enter;
    QPushButton *pushButton_s;
    QPushButton *pushButton_l;
    QPushButton *pushButton_d;
    QPushButton *pushButton_m;
    QPushButton *pushButton_b;
    QPushButton *pushButton_n;
    QPushButton *pushButton_comma;
    QPushButton *pushButton_z;
    QPushButton *pushButton_splash;
    QPushButton *pushButton_v;
    QPushButton *pushButton_x;
    QPushButton *pushButton_period;
    QPushButton *pushButton_c;
    QPushButton *pushButton_shift;
    QPushButton *pushButton_whitespace;
    QPushButton *pushButton_backsplash;
    QPushButton *pushButton_n2;
    QPushButton *pushButton_is_hanzi;
    QPushButton *pushButton_ok;
    QPushButton *pushButton_hanzi_7;
    QPushButton *pushButton_hanzi_5;
    QPushButton *pushButton_hanzi_6;
    QPushButton *pushButton_hanzi_8;
    QPushButton *pushButton_hanzi_4;
    QPushButton *pushButton_hanzi_2;
    QPushButton *pushButton_hanzi_3;
    QPushButton *pushButton_hanzi_left;
    QPushButton *pushButton_hanzi_right;
    QPushButton *pushButton_hanzi_1;
    QPushButton *pushButton_n3;
    QPushButton *pushButton_backspace;
    QPushButton *pushButton_n0;
    QPushButton *pushButton_n1;
    QPushButton *pushButton_n6;
    QPushButton *pushButton_deng;
    QPushButton *pushButton_gang;
    QPushButton *pushButton_n5;
    QPushButton *pushButton_n7;
    QPushButton *pushButton_n8;
    QPushButton *pushButton_n4;
    QPushButton *pushButton_n9;
    QPushButton *pushButton_left;
    QPushButton *pushButton_right;
    QPushButton *pushButton_up;
    QPushButton *pushButton_down;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QString::fromUtf8("Dialog"));
        Dialog->resize(800, 239);
        pushButton_u = new QPushButton(Dialog);
        pushButton_u->setObjectName(QString::fromUtf8("pushButton_u"));
        pushButton_u->setGeometry(QRect(319, 41, 45, 45));
        QFont font;
        font.setPointSize(20);
        font.setBold(true);
        font.setWeight(75);
        pushButton_u->setFont(font);
        pushButton_t = new QPushButton(Dialog);
        pushButton_t->setObjectName(QString::fromUtf8("pushButton_t"));
        pushButton_t->setGeometry(QRect(218, 41, 45, 45));
        pushButton_t->setFont(font);
        pushButton_y = new QPushButton(Dialog);
        pushButton_y->setObjectName(QString::fromUtf8("pushButton_y"));
        pushButton_y->setGeometry(QRect(268, 41, 45, 45));
        pushButton_y->setFont(font);
        pushButton_i = new QPushButton(Dialog);
        pushButton_i->setObjectName(QString::fromUtf8("pushButton_i"));
        pushButton_i->setGeometry(QRect(369, 41, 45, 45));
        pushButton_i->setFont(font);
        pushButton_q = new QPushButton(Dialog);
        pushButton_q->setObjectName(QString::fromUtf8("pushButton_q"));
        pushButton_q->setGeometry(QRect(16, 41, 45, 45));
        pushButton_q->setFont(font);
        pushButton_zuokuo = new QPushButton(Dialog);
        pushButton_zuokuo->setObjectName(QString::fromUtf8("pushButton_zuokuo"));
        pushButton_zuokuo->setGeometry(QRect(520, 40, 45, 45));
        pushButton_zuokuo->setFont(font);
        pushButton_p = new QPushButton(Dialog);
        pushButton_p->setObjectName(QString::fromUtf8("pushButton_p"));
        pushButton_p->setGeometry(QRect(470, 41, 45, 45));
        pushButton_p->setFont(font);
        pushButton_r = new QPushButton(Dialog);
        pushButton_r->setObjectName(QString::fromUtf8("pushButton_r"));
        pushButton_r->setGeometry(QRect(168, 41, 45, 45));
        pushButton_r->setFont(font);
        pushButton_youkuo = new QPushButton(Dialog);
        pushButton_youkuo->setObjectName(QString::fromUtf8("pushButton_youkuo"));
        pushButton_youkuo->setGeometry(QRect(570, 40, 45, 45));
        pushButton_youkuo->setFont(font);
        pushButton_w = new QPushButton(Dialog);
        pushButton_w->setObjectName(QString::fromUtf8("pushButton_w"));
        pushButton_w->setGeometry(QRect(67, 41, 45, 45));
        pushButton_w->setFont(font);
        pushButton_o = new QPushButton(Dialog);
        pushButton_o->setObjectName(QString::fromUtf8("pushButton_o"));
        pushButton_o->setGeometry(QRect(420, 41, 45, 45));
        pushButton_o->setFont(font);
        pushButton_e = new QPushButton(Dialog);
        pushButton_e->setObjectName(QString::fromUtf8("pushButton_e"));
        pushButton_e->setGeometry(QRect(117, 41, 45, 45));
        pushButton_e->setFont(font);
        pushButton_j = new QPushButton(Dialog);
        pushButton_j->setObjectName(QString::fromUtf8("pushButton_j"));
        pushButton_j->setGeometry(QRect(342, 90, 45, 45));
        pushButton_j->setFont(font);
        pushButton_g = new QPushButton(Dialog);
        pushButton_g->setObjectName(QString::fromUtf8("pushButton_g"));
        pushButton_g->setGeometry(QRect(241, 90, 45, 45));
        pushButton_g->setFont(font);
        pushButton_h = new QPushButton(Dialog);
        pushButton_h->setObjectName(QString::fromUtf8("pushButton_h"));
        pushButton_h->setGeometry(QRect(291, 90, 45, 45));
        pushButton_h->setFont(font);
        pushButton_k = new QPushButton(Dialog);
        pushButton_k->setObjectName(QString::fromUtf8("pushButton_k"));
        pushButton_k->setGeometry(QRect(392, 90, 45, 45));
        pushButton_k->setFont(font);
        pushButton_a = new QPushButton(Dialog);
        pushButton_a->setObjectName(QString::fromUtf8("pushButton_a"));
        pushButton_a->setGeometry(QRect(39, 90, 45, 45));
        pushButton_a->setFont(font);
        pushButton_quote = new QPushButton(Dialog);
        pushButton_quote->setObjectName(QString::fromUtf8("pushButton_quote"));
        pushButton_quote->setGeometry(QRect(550, 90, 45, 45));
        pushButton_quote->setFont(font);
        pushButton_semicolon = new QPushButton(Dialog);
        pushButton_semicolon->setObjectName(QString::fromUtf8("pushButton_semicolon"));
        pushButton_semicolon->setGeometry(QRect(500, 90, 45, 45));
        pushButton_semicolon->setFont(font);
        pushButton_f = new QPushButton(Dialog);
        pushButton_f->setObjectName(QString::fromUtf8("pushButton_f"));
        pushButton_f->setGeometry(QRect(191, 90, 45, 45));
        pushButton_f->setFont(font);
        pushButton_enter = new QPushButton(Dialog);
        pushButton_enter->setObjectName(QString::fromUtf8("pushButton_enter"));
        pushButton_enter->setGeometry(QRect(590, 140, 51, 35));
        pushButton_enter->setFont(font);
        pushButton_s = new QPushButton(Dialog);
        pushButton_s->setObjectName(QString::fromUtf8("pushButton_s"));
        pushButton_s->setGeometry(QRect(90, 90, 45, 45));
        pushButton_s->setFont(font);
        pushButton_l = new QPushButton(Dialog);
        pushButton_l->setObjectName(QString::fromUtf8("pushButton_l"));
        pushButton_l->setGeometry(QRect(443, 90, 45, 45));
        pushButton_l->setFont(font);
        pushButton_d = new QPushButton(Dialog);
        pushButton_d->setObjectName(QString::fromUtf8("pushButton_d"));
        pushButton_d->setGeometry(QRect(140, 90, 45, 45));
        pushButton_d->setFont(font);
        pushButton_m = new QPushButton(Dialog);
        pushButton_m->setObjectName(QString::fromUtf8("pushButton_m"));
        pushButton_m->setGeometry(QRect(360, 140, 45, 45));
        pushButton_m->setFont(font);
        pushButton_b = new QPushButton(Dialog);
        pushButton_b->setObjectName(QString::fromUtf8("pushButton_b"));
        pushButton_b->setGeometry(QRect(260, 140, 45, 45));
        pushButton_b->setFont(font);
        pushButton_b->setFlat(false);
        pushButton_n = new QPushButton(Dialog);
        pushButton_n->setObjectName(QString::fromUtf8("pushButton_n"));
        pushButton_n->setGeometry(QRect(310, 140, 45, 45));
        pushButton_n->setFont(font);
        pushButton_comma = new QPushButton(Dialog);
        pushButton_comma->setObjectName(QString::fromUtf8("pushButton_comma"));
        pushButton_comma->setGeometry(QRect(360, 190, 45, 45));
        pushButton_comma->setFont(font);
        pushButton_z = new QPushButton(Dialog);
        pushButton_z->setObjectName(QString::fromUtf8("pushButton_z"));
        pushButton_z->setGeometry(QRect(60, 140, 45, 45));
        pushButton_z->setFont(font);
        pushButton_splash = new QPushButton(Dialog);
        pushButton_splash->setObjectName(QString::fromUtf8("pushButton_splash"));
        pushButton_splash->setGeometry(QRect(470, 140, 45, 45));
        pushButton_splash->setFont(font);
        pushButton_v = new QPushButton(Dialog);
        pushButton_v->setObjectName(QString::fromUtf8("pushButton_v"));
        pushButton_v->setGeometry(QRect(210, 140, 45, 45));
        pushButton_v->setFont(font);
        pushButton_x = new QPushButton(Dialog);
        pushButton_x->setObjectName(QString::fromUtf8("pushButton_x"));
        pushButton_x->setGeometry(QRect(110, 140, 45, 45));
        pushButton_x->setFont(font);
        pushButton_period = new QPushButton(Dialog);
        pushButton_period->setObjectName(QString::fromUtf8("pushButton_period"));
        pushButton_period->setGeometry(QRect(754, 190, 41, 45));
        pushButton_period->setFont(font);
        pushButton_c = new QPushButton(Dialog);
        pushButton_c->setObjectName(QString::fromUtf8("pushButton_c"));
        pushButton_c->setGeometry(QRect(160, 140, 45, 45));
        pushButton_c->setFont(font);
        pushButton_shift = new QPushButton(Dialog);
        pushButton_shift->setObjectName(QString::fromUtf8("pushButton_shift"));
        pushButton_shift->setGeometry(QRect(20, 190, 61, 45));
        pushButton_shift->setFont(font);
        pushButton_whitespace = new QPushButton(Dialog);
        pushButton_whitespace->setObjectName(QString::fromUtf8("pushButton_whitespace"));
        pushButton_whitespace->setGeometry(QRect(90, 190, 171, 45));
        pushButton_whitespace->setFont(font);
        pushButton_backsplash = new QPushButton(Dialog);
        pushButton_backsplash->setObjectName(QString::fromUtf8("pushButton_backsplash"));
        pushButton_backsplash->setGeometry(QRect(410, 140, 45, 45));
        pushButton_backsplash->setFont(font);
        pushButton_n2 = new QPushButton(Dialog);
        pushButton_n2->setObjectName(QString::fromUtf8("pushButton_n2"));
        pushButton_n2->setGeometry(QRect(700, 140, 45, 45));
        pushButton_n2->setFont(font);
        pushButton_n2->setFocusPolicy(Qt::ClickFocus);
        pushButton_is_hanzi = new QPushButton(Dialog);
        pushButton_is_hanzi->setObjectName(QString::fromUtf8("pushButton_is_hanzi"));
        pushButton_is_hanzi->setGeometry(QRect(270, 190, 81, 45));
        QFont font1;
        font1.setPointSize(15);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_is_hanzi->setFont(font1);
        pushButton_ok = new QPushButton(Dialog);
        pushButton_ok->setObjectName(QString::fromUtf8("pushButton_ok"));
        pushButton_ok->setGeometry(QRect(660, 0, 131, 35));
        QPalette palette;
        QBrush brush(QColor(0, 255, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(118, 116, 108, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_ok->setPalette(palette);
        QFont font2;
        font2.setFamily(QString::fromUtf8("Abyssinica SIL"));
        font2.setPointSize(20);
        font2.setBold(false);
        font2.setWeight(50);
        pushButton_ok->setFont(font2);
        pushButton_hanzi_7 = new QPushButton(Dialog);
        pushButton_hanzi_7->setObjectName(QString::fromUtf8("pushButton_hanzi_7"));
        pushButton_hanzi_7->setGeometry(QRect(392, 0, 45, 35));
        pushButton_hanzi_7->setFont(font1);
        pushButton_hanzi_5 = new QPushButton(Dialog);
        pushButton_hanzi_5->setObjectName(QString::fromUtf8("pushButton_hanzi_5"));
        pushButton_hanzi_5->setGeometry(QRect(291, 0, 45, 35));
        pushButton_hanzi_5->setFont(font1);
        pushButton_hanzi_6 = new QPushButton(Dialog);
        pushButton_hanzi_6->setObjectName(QString::fromUtf8("pushButton_hanzi_6"));
        pushButton_hanzi_6->setGeometry(QRect(341, 0, 45, 35));
        pushButton_hanzi_6->setFont(font1);
        pushButton_hanzi_8 = new QPushButton(Dialog);
        pushButton_hanzi_8->setObjectName(QString::fromUtf8("pushButton_hanzi_8"));
        pushButton_hanzi_8->setGeometry(QRect(442, 0, 45, 35));
        pushButton_hanzi_8->setFont(font1);
        pushButton_hanzi_4 = new QPushButton(Dialog);
        pushButton_hanzi_4->setObjectName(QString::fromUtf8("pushButton_hanzi_4"));
        pushButton_hanzi_4->setGeometry(QRect(241, 0, 45, 35));
        pushButton_hanzi_4->setFont(font1);
        pushButton_hanzi_2 = new QPushButton(Dialog);
        pushButton_hanzi_2->setObjectName(QString::fromUtf8("pushButton_hanzi_2"));
        pushButton_hanzi_2->setGeometry(QRect(140, 0, 45, 35));
        pushButton_hanzi_2->setFont(font1);
        pushButton_hanzi_3 = new QPushButton(Dialog);
        pushButton_hanzi_3->setObjectName(QString::fromUtf8("pushButton_hanzi_3"));
        pushButton_hanzi_3->setGeometry(QRect(190, 0, 45, 35));
        pushButton_hanzi_3->setFont(font1);
        pushButton_hanzi_left = new QPushButton(Dialog);
        pushButton_hanzi_left->setObjectName(QString::fromUtf8("pushButton_hanzi_left"));
        pushButton_hanzi_left->setGeometry(QRect(17, 0, 70, 35));
        pushButton_hanzi_left->setFont(font);
        pushButton_hanzi_right = new QPushButton(Dialog);
        pushButton_hanzi_right->setObjectName(QString::fromUtf8("pushButton_hanzi_right"));
        pushButton_hanzi_right->setGeometry(QRect(490, 0, 70, 35));
        pushButton_hanzi_right->setFont(font);
        pushButton_hanzi_1 = new QPushButton(Dialog);
        pushButton_hanzi_1->setObjectName(QString::fromUtf8("pushButton_hanzi_1"));
        pushButton_hanzi_1->setGeometry(QRect(90, 0, 45, 35));
        pushButton_hanzi_1->setFont(font1);
        pushButton_n3 = new QPushButton(Dialog);
        pushButton_n3->setObjectName(QString::fromUtf8("pushButton_n3"));
        pushButton_n3->setGeometry(QRect(750, 140, 45, 45));
        pushButton_n3->setFont(font);
        pushButton_backspace = new QPushButton(Dialog);
        pushButton_backspace->setObjectName(QString::fromUtf8("pushButton_backspace"));
        pushButton_backspace->setGeometry(QRect(560, 0, 91, 35));
        QFont font3;
        font3.setFamily(QString::fromUtf8("PT Sans"));
        font3.setPointSize(20);
        font3.setBold(true);
        font3.setWeight(75);
        pushButton_backspace->setFont(font3);
        pushButton_backspace->setMouseTracking(false);
        pushButton_n0 = new QPushButton(Dialog);
        pushButton_n0->setObjectName(QString::fromUtf8("pushButton_n0"));
        pushButton_n0->setGeometry(QRect(700, 190, 45, 45));
        pushButton_n0->setFont(font);
        pushButton_n1 = new QPushButton(Dialog);
        pushButton_n1->setObjectName(QString::fromUtf8("pushButton_n1"));
        pushButton_n1->setGeometry(QRect(650, 140, 45, 45));
        pushButton_n1->setFont(font);
        pushButton_n1->setFocusPolicy(Qt::ClickFocus);
        pushButton_n6 = new QPushButton(Dialog);
        pushButton_n6->setObjectName(QString::fromUtf8("pushButton_n6"));
        pushButton_n6->setGeometry(QRect(750, 90, 45, 45));
        pushButton_n6->setFont(font);
        pushButton_deng = new QPushButton(Dialog);
        pushButton_deng->setObjectName(QString::fromUtf8("pushButton_deng"));
        pushButton_deng->setGeometry(QRect(410, 190, 45, 45));
        pushButton_deng->setFont(font);
        pushButton_gang = new QPushButton(Dialog);
        pushButton_gang->setObjectName(QString::fromUtf8("pushButton_gang"));
        pushButton_gang->setGeometry(QRect(650, 190, 45, 45));
        pushButton_gang->setFont(font);
        pushButton_n5 = new QPushButton(Dialog);
        pushButton_n5->setObjectName(QString::fromUtf8("pushButton_n5"));
        pushButton_n5->setGeometry(QRect(700, 90, 45, 45));
        pushButton_n5->setFont(font);
        pushButton_n7 = new QPushButton(Dialog);
        pushButton_n7->setObjectName(QString::fromUtf8("pushButton_n7"));
        pushButton_n7->setGeometry(QRect(650, 40, 45, 45));
        pushButton_n7->setFont(font);
        pushButton_n8 = new QPushButton(Dialog);
        pushButton_n8->setObjectName(QString::fromUtf8("pushButton_n8"));
        pushButton_n8->setGeometry(QRect(700, 40, 45, 45));
        pushButton_n8->setFont(font);
        pushButton_n4 = new QPushButton(Dialog);
        pushButton_n4->setObjectName(QString::fromUtf8("pushButton_n4"));
        pushButton_n4->setGeometry(QRect(650, 90, 45, 45));
        pushButton_n4->setFont(font);
        pushButton_n9 = new QPushButton(Dialog);
        pushButton_n9->setObjectName(QString::fromUtf8("pushButton_n9"));
        pushButton_n9->setGeometry(QRect(750, 40, 45, 45));
        pushButton_n9->setFont(font);
        pushButton_left = new QPushButton(Dialog);
        pushButton_left->setObjectName(QString::fromUtf8("pushButton_left"));
        pushButton_left->setGeometry(QRect(460, 190, 60, 45));
        pushButton_left->setFont(font);
        pushButton_right = new QPushButton(Dialog);
        pushButton_right->setObjectName(QString::fromUtf8("pushButton_right"));
        pushButton_right->setGeometry(QRect(580, 190, 60, 45));
        pushButton_right->setFont(font);
        pushButton_up = new QPushButton(Dialog);
        pushButton_up->setObjectName(QString::fromUtf8("pushButton_up"));
        pushButton_up->setGeometry(QRect(520, 140, 60, 45));
        pushButton_up->setFont(font);
        pushButton_down = new QPushButton(Dialog);
        pushButton_down->setObjectName(QString::fromUtf8("pushButton_down"));
        pushButton_down->setGeometry(QRect(520, 190, 60, 45));
        pushButton_down->setFont(font);
        QWidget::setTabOrder(pushButton_hanzi_left, pushButton_hanzi_1);
        QWidget::setTabOrder(pushButton_hanzi_1, pushButton_hanzi_2);
        QWidget::setTabOrder(pushButton_hanzi_2, pushButton_hanzi_3);
        QWidget::setTabOrder(pushButton_hanzi_3, pushButton_hanzi_4);
        QWidget::setTabOrder(pushButton_hanzi_4, pushButton_hanzi_5);
        QWidget::setTabOrder(pushButton_hanzi_5, pushButton_hanzi_6);
        QWidget::setTabOrder(pushButton_hanzi_6, pushButton_hanzi_7);
        QWidget::setTabOrder(pushButton_hanzi_7, pushButton_hanzi_8);
        QWidget::setTabOrder(pushButton_hanzi_8, pushButton_hanzi_right);
        QWidget::setTabOrder(pushButton_hanzi_right, pushButton_n1);
        QWidget::setTabOrder(pushButton_n1, pushButton_n2);
        QWidget::setTabOrder(pushButton_n2, pushButton_n3);
        QWidget::setTabOrder(pushButton_n3, pushButton_n4);
        QWidget::setTabOrder(pushButton_n4, pushButton_n5);
        QWidget::setTabOrder(pushButton_n5, pushButton_n6);
        QWidget::setTabOrder(pushButton_n6, pushButton_n7);
        QWidget::setTabOrder(pushButton_n7, pushButton_n8);
        QWidget::setTabOrder(pushButton_n8, pushButton_n9);
        QWidget::setTabOrder(pushButton_n9, pushButton_n0);
        QWidget::setTabOrder(pushButton_n0, pushButton_gang);
        QWidget::setTabOrder(pushButton_gang, pushButton_deng);
        QWidget::setTabOrder(pushButton_deng, pushButton_backspace);
        QWidget::setTabOrder(pushButton_backspace, pushButton_q);
        QWidget::setTabOrder(pushButton_q, pushButton_w);
        QWidget::setTabOrder(pushButton_w, pushButton_e);
        QWidget::setTabOrder(pushButton_e, pushButton_r);
        QWidget::setTabOrder(pushButton_r, pushButton_t);
        QWidget::setTabOrder(pushButton_t, pushButton_y);
        QWidget::setTabOrder(pushButton_y, pushButton_u);
        QWidget::setTabOrder(pushButton_u, pushButton_i);
        QWidget::setTabOrder(pushButton_i, pushButton_o);
        QWidget::setTabOrder(pushButton_o, pushButton_p);
        QWidget::setTabOrder(pushButton_p, pushButton_zuokuo);
        QWidget::setTabOrder(pushButton_zuokuo, pushButton_youkuo);
        QWidget::setTabOrder(pushButton_youkuo, pushButton_backsplash);
        QWidget::setTabOrder(pushButton_backsplash, pushButton_a);
        QWidget::setTabOrder(pushButton_a, pushButton_s);
        QWidget::setTabOrder(pushButton_s, pushButton_d);
        QWidget::setTabOrder(pushButton_d, pushButton_f);
        QWidget::setTabOrder(pushButton_f, pushButton_g);
        QWidget::setTabOrder(pushButton_g, pushButton_h);
        QWidget::setTabOrder(pushButton_h, pushButton_j);
        QWidget::setTabOrder(pushButton_j, pushButton_k);
        QWidget::setTabOrder(pushButton_k, pushButton_l);
        QWidget::setTabOrder(pushButton_l, pushButton_semicolon);
        QWidget::setTabOrder(pushButton_semicolon, pushButton_quote);
        QWidget::setTabOrder(pushButton_quote, pushButton_enter);
        QWidget::setTabOrder(pushButton_enter, pushButton_z);
        QWidget::setTabOrder(pushButton_z, pushButton_x);
        QWidget::setTabOrder(pushButton_x, pushButton_c);
        QWidget::setTabOrder(pushButton_c, pushButton_v);
        QWidget::setTabOrder(pushButton_v, pushButton_b);
        QWidget::setTabOrder(pushButton_b, pushButton_n);
        QWidget::setTabOrder(pushButton_n, pushButton_m);
        QWidget::setTabOrder(pushButton_m, pushButton_comma);
        QWidget::setTabOrder(pushButton_comma, pushButton_period);
        QWidget::setTabOrder(pushButton_period, pushButton_splash);
        QWidget::setTabOrder(pushButton_splash, pushButton_shift);
        QWidget::setTabOrder(pushButton_shift, pushButton_whitespace);
        QWidget::setTabOrder(pushButton_whitespace, pushButton_is_hanzi);
        QWidget::setTabOrder(pushButton_is_hanzi, pushButton_ok);

        retranslateUi(Dialog);

        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Dialog", 0, QApplication::UnicodeUTF8));
        pushButton_u->setText(QApplication::translate("Dialog", "u", 0, QApplication::UnicodeUTF8));
        pushButton_t->setText(QApplication::translate("Dialog", "t", 0, QApplication::UnicodeUTF8));
        pushButton_y->setText(QApplication::translate("Dialog", "y", 0, QApplication::UnicodeUTF8));
        pushButton_i->setText(QApplication::translate("Dialog", "i", 0, QApplication::UnicodeUTF8));
        pushButton_q->setText(QApplication::translate("Dialog", "q", 0, QApplication::UnicodeUTF8));
        pushButton_zuokuo->setText(QApplication::translate("Dialog", "[", 0, QApplication::UnicodeUTF8));
        pushButton_p->setText(QApplication::translate("Dialog", "p", 0, QApplication::UnicodeUTF8));
        pushButton_r->setText(QApplication::translate("Dialog", "r", 0, QApplication::UnicodeUTF8));
        pushButton_youkuo->setText(QApplication::translate("Dialog", "]", 0, QApplication::UnicodeUTF8));
        pushButton_w->setText(QApplication::translate("Dialog", "w", 0, QApplication::UnicodeUTF8));
        pushButton_o->setText(QApplication::translate("Dialog", "o", 0, QApplication::UnicodeUTF8));
        pushButton_e->setText(QApplication::translate("Dialog", "e", 0, QApplication::UnicodeUTF8));
        pushButton_j->setText(QApplication::translate("Dialog", "j", 0, QApplication::UnicodeUTF8));
        pushButton_g->setText(QApplication::translate("Dialog", "g", 0, QApplication::UnicodeUTF8));
        pushButton_h->setText(QApplication::translate("Dialog", "h", 0, QApplication::UnicodeUTF8));
        pushButton_k->setText(QApplication::translate("Dialog", "k", 0, QApplication::UnicodeUTF8));
        pushButton_a->setText(QApplication::translate("Dialog", "a", 0, QApplication::UnicodeUTF8));
        pushButton_quote->setText(QApplication::translate("Dialog", "'", 0, QApplication::UnicodeUTF8));
        pushButton_semicolon->setText(QApplication::translate("Dialog", ";", 0, QApplication::UnicodeUTF8));
        pushButton_f->setText(QApplication::translate("Dialog", "f", 0, QApplication::UnicodeUTF8));
        pushButton_enter->setText(QApplication::translate("Dialog", "enter", 0, QApplication::UnicodeUTF8));
        pushButton_s->setText(QApplication::translate("Dialog", "s", 0, QApplication::UnicodeUTF8));
        pushButton_l->setText(QApplication::translate("Dialog", "l", 0, QApplication::UnicodeUTF8));
        pushButton_d->setText(QApplication::translate("Dialog", "d", 0, QApplication::UnicodeUTF8));
        pushButton_m->setText(QApplication::translate("Dialog", "m", 0, QApplication::UnicodeUTF8));
        pushButton_b->setText(QApplication::translate("Dialog", "b", 0, QApplication::UnicodeUTF8));
        pushButton_n->setText(QApplication::translate("Dialog", "n", 0, QApplication::UnicodeUTF8));
        pushButton_comma->setText(QApplication::translate("Dialog", ",", 0, QApplication::UnicodeUTF8));
        pushButton_z->setText(QApplication::translate("Dialog", "z", 0, QApplication::UnicodeUTF8));
        pushButton_splash->setText(QApplication::translate("Dialog", "/", 0, QApplication::UnicodeUTF8));
        pushButton_v->setText(QApplication::translate("Dialog", "v", 0, QApplication::UnicodeUTF8));
        pushButton_x->setText(QApplication::translate("Dialog", "x", 0, QApplication::UnicodeUTF8));
        pushButton_period->setText(QApplication::translate("Dialog", ".", 0, QApplication::UnicodeUTF8));
        pushButton_c->setText(QApplication::translate("Dialog", "c", 0, QApplication::UnicodeUTF8));
        pushButton_shift->setText(QApplication::translate("Dialog", "shift", 0, QApplication::UnicodeUTF8));
        pushButton_whitespace->setText(QApplication::translate("Dialog", "whitespace", 0, QApplication::UnicodeUTF8));
        pushButton_backsplash->setText(QApplication::translate("Dialog", "\\", 0, QApplication::UnicodeUTF8));
        pushButton_n2->setText(QApplication::translate("Dialog", "2", 0, QApplication::UnicodeUTF8));
        pushButton_is_hanzi->setText(QApplication::translate("Dialog", "En", 0, QApplication::UnicodeUTF8));
        pushButton_ok->setText(QApplication::translate("Dialog", "\347\241\256\350\256\244", 0, QApplication::UnicodeUTF8));
        pushButton_hanzi_7->setText(QString());
        pushButton_hanzi_5->setText(QString());
        pushButton_hanzi_6->setText(QString());
        pushButton_hanzi_8->setText(QString());
        pushButton_hanzi_4->setText(QString());
        pushButton_hanzi_2->setText(QString());
        pushButton_hanzi_3->setText(QString());
        pushButton_hanzi_left->setText(QApplication::translate("Dialog", "\342\206\220", 0, QApplication::UnicodeUTF8));
        pushButton_hanzi_right->setText(QApplication::translate("Dialog", "\342\206\222", 0, QApplication::UnicodeUTF8));
        pushButton_hanzi_1->setText(QString());
        pushButton_n3->setText(QApplication::translate("Dialog", "3", 0, QApplication::UnicodeUTF8));
        pushButton_backspace->setText(QApplication::translate("Dialog", "DeL", 0, QApplication::UnicodeUTF8));
        pushButton_n0->setText(QApplication::translate("Dialog", "0", 0, QApplication::UnicodeUTF8));
        pushButton_n1->setText(QApplication::translate("Dialog", "1", 0, QApplication::UnicodeUTF8));
        pushButton_n6->setText(QApplication::translate("Dialog", "6", 0, QApplication::UnicodeUTF8));
        pushButton_deng->setText(QApplication::translate("Dialog", "=", 0, QApplication::UnicodeUTF8));
        pushButton_gang->setText(QApplication::translate("Dialog", "-", 0, QApplication::UnicodeUTF8));
        pushButton_n5->setText(QApplication::translate("Dialog", "5", 0, QApplication::UnicodeUTF8));
        pushButton_n7->setText(QApplication::translate("Dialog", "7", 0, QApplication::UnicodeUTF8));
        pushButton_n8->setText(QApplication::translate("Dialog", "8", 0, QApplication::UnicodeUTF8));
        pushButton_n4->setText(QApplication::translate("Dialog", "4", 0, QApplication::UnicodeUTF8));
        pushButton_n9->setText(QApplication::translate("Dialog", "9", 0, QApplication::UnicodeUTF8));
        pushButton_left->setText(QApplication::translate("Dialog", "\342\206\220", 0, QApplication::UnicodeUTF8));
        pushButton_right->setText(QApplication::translate("Dialog", "\342\206\222", 0, QApplication::UnicodeUTF8));
        pushButton_up->setText(QApplication::translate("Dialog", "\342\206\221", 0, QApplication::UnicodeUTF8));
        pushButton_down->setText(QApplication::translate("Dialog", "\342\206\223", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SOFTKEYBOARD_H
